version: '3.1'
services:
  heservice:
    container_name: heservice
    restart: on-failure
    image: jovixe/he_services:7529949
    env_file:
      - ./.env
    depends_on:
      - mariadb
    ports:
      - 8002:8080
  rabbitmq:
    image: rabbitmq:3.10.6-management
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  mariadb:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
      - ./mariadb.schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
  processor:
    image: jovixe/paymentgw:14a4341
    restart: always
    container_name: processor
    env_file:
      - ./.env
    volumes:
      - ./integrator_scripts:/integrator_scripts:ro
    depends_on:
      - rabbitmq
      - mariadb
      # - redis
    ports:
      - 8001:8080
  # redis:
  #   image: redis
  #   restart: always
  #   command: >
  #     --requirepass ${REDIS_PASSWORD}
  #   depends_on:
  #     - mariadb
  adminer:
    image: adminer
    restart: always
    depends_on:
      - upsert
      - mariadb
    ports:
      - 8082:8080
  upsert:
    container_name: upsert
    restart: on-failure
    image: jovixe/trx-upsert:6ef0798
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
